### ISSUE TITLE
Feature request: Ability to add description below title of class

### ISSUE THREAD

**Issue by bikrrr** [SakiTakamachi/class-diagram-template-figma#1]
I'd like the ability to enter a description for each class to display below the title, possibly something like this: 

<img width="494" alt="Class Diagram Description" src="https://github.com/SakiTakamachi/class-diagram-template-figma/assets/2607653/bbaf5783-69a1-457d-8bc3-d6ff65b04d82">

**Comment by SakiTakamachi** [comment]
@bikrrr 
Implementation was delayed. Added class description function.

**Comment by SakiTakamachi** [comment]
Unfortunately, widgets that have already been inserted seem to remain in their previous version.
https://www.figma.com/widget-docs/stability-and-updates/

**Comment by SakiTakamachi** [comment]
I didn't know this! Thank you for tell me:)
